name: Ping TeknoSeyir & Update JSON
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  ping_and_update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Ping TeknoSeyir and get status code
      id: ping
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://teknoseyir.com/)
        echo "Ping response: $response"
        echo "::set-output name=status_code::$response"
    
    - name: Update read.json with ping result
      run: |
        timestamp=$(date +"%d.%m.%Y %H:%M:%S")
        status_code="${{ steps.ping.outputs.status_code }}"
        json_data="{\"date\": \"$timestamp\", \"text\": \"ERROR: $status_code\"}"
        
        # Check if the response is 200, otherwise log error status
        if [[ "$status_code" == "200" ]]; then
          json_data="{\"date\": \"$timestamp\", \"text\": \"OK\"}"
        fi
        
        # Add new entry to the JSON file
        if [ -f ts/read.json ]; then
          jq ". += [$json_data]" ts/read.json > tmp.json && mv tmp.json ts/read.json
        else
          echo "[]$json_data" > ts/read.json
        fi

    - name: Commit changes and push
      run: |
        git config user.name 'tsopen'
        git config user.email 'tsopenteam@gmail.com'
        git add ts/read.json
        git commit -m "bot: update read.json with new ping result"
        git push
